---
# PersistentVolumeClaim для Keycloak
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-pvc
  namespace: keycloak-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
# ConfigMap для конфигурации Keycloak
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-config
  namespace: keycloak-namespace
data:
  realm.json: |
    {
      "realm": "model-registry-realm",
      "enabled": true,
      "sslRequired": "external",
      "registrationAllowed": false,
      "loginWithEmailAllowed": true,
      "duplicateEmailsAllowed": false,
      "resetPasswordAllowed": true,
      "editUsernameAllowed": false,
      "bruteForceProtected": true,
      "clients": [
        {
          "clientId": "model-registry-app",
          "enabled": true,
          "protocol": "openid-connect",
          "publicClient": true,
          "secret": "LZbXY16jR0BRFazUKO3qTAoqXL3Uoet7",
          "redirectUris": ["*"],
          "webOrigins": ["*"],
          "standardFlowEnabled": true,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": true,
          "serviceAccountsEnabled": true,
          "authorizationServicesEnabled": true,
          "fullScopeAllowed": true,
          "protocolMappers": [
            {
              "name": "audience-mapper",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-audience-mapper",
              "config": {
                "included.client.audience": "model-registry-app",
                "id.token.claim": "false",
                "access.token.claim": "true"
              }
            }
          ]
        }
      ],
      "roles": {
        "realm": [
          {
            "name": "data-scientist",
            "description": "Data Scientist role"
          },
          {
            "name": "system-administrator",
            "description": "System Administrator role"
          },
          {
            "name": "user",
            "description": "Regular user role"
          }
        ]
      },
      "users": [
        {
          "username": "alice",
          "enabled": true,
          "email": "alice@example.com",
          "firstName": "Alice",
          "lastName": "DataScientist",
          "credentials": [
            {
              "type": "password",
              "value": "alice",
              "temporary": false
            }
          ],
          "realmRoles": ["data-scientist"]
        },
        {
          "username": "bob",
          "enabled": true,
          "email": "bob@example.com",
          "firstName": "Bob",
          "lastName": "SystemAdministrator",
          "credentials": [
            {
              "type": "password",
              "value": "bob",
              "temporary": false
            }
          ],
          "realmRoles": ["system-administrator"]
        },
        {
          "username": "carol",
          "enabled": true,
          "email": "carol@example.com",
          "firstName": "Carol",
          "lastName": "User",
          "credentials": [
            {
              "type": "password",
              "value": "carol",
              "temporary": false
            }
          ],
          "realmRoles": ["user"]
        }
      ]
    }

---
# Service для Keycloak
apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: keycloak-namespace
  labels:
    app: keycloak
spec:
  selector:
    app: keycloak
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: https
      port: 8443
      targetPort: 8443

---
# Deployment для Keycloak
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
  namespace: keycloak-namespace
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.3.1
          ports:
            - containerPort: 8080
            - containerPort: 8443
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL
              value: "jdbc:postgresql://postgres-service:5432/keycloak_db"
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: POSTGRES_USER
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: POSTGRES_PASSWORD
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"
            - name: KC_PROXY
              value: "edge"
            - name: KC_HTTP_ENABLED
              value: "true"
          volumeMounts:
            - name: keycloak-storage
              mountPath: /opt/keycloak/data
            - name: realm-config-volume
              mountPath: /opt/keycloak/data/import
          args: ["start", "--import-realm"]
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /realms/master
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
      volumes:
        - name: keycloak-storage
          persistentVolumeClaim:
            claimName: keycloak-pvc
        - name: realm-config-volume
          configMap:
            name: keycloak-realm-config