apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda-console
  namespace: model-registry
  labels:
    app: redpanda-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda-console
  template:
    metadata:
      labels:
        app: redpanda-console
    spec:
      containers:
      - name: redpanda-console
        image: docker.redpanda.com/redpandadata/console:v2.6.0
        env:
        - name: KAFKA_BROKERS
          value: "redpanda.model-registry.svc.cluster.local:9092"
        - name: CONFIG_FILEPATH
          value: "/etc/console/config.yaml"
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: console-config
          mountPath: /etc/console
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: console-config
        configMap:
          name: redpanda-console-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redpanda-console-config
  namespace: model-registry
data:
  config.yaml: |
    kafka:
      brokers: ["redpanda.model-registry.svc.cluster.local:9092"]
      tls:
        enabled: false
      sasl:
        enabled: false
    
    
    redpanda:
      adminApi:
        enabled: true
        urls: ["http://redpanda.model-registry.svc.cluster.local:9644"]
---
apiVersion: v1
kind: Service
metadata:
  name: redpanda-console
  namespace: model-registry
  labels:
    app: redpanda-console
spec:
  selector:
    app: redpanda-console
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redpanda-console-ingress
  namespace: model-registry
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: kafka.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: redpanda-console
            port:
              number: 8080