apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
  namespace: user-inference-ns
spec:
  storageClassName: local-path 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi